import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description:
    "Terms and Conditions for using the InpromptiFy platform, including account terms, acceptable use, assessment integrity, and more.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-24 pb-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6">
        {/* Header */}
        <div className="mb-16">
          <span className="section-label">[ Legal ]</span>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight mt-2 text-white leading-tight">
            Terms and Conditions
          </h1>
          <p className="text-lg text-gray-400 mt-6 leading-relaxed">
            Effective Date: April 20, 2026
          </p>
        </div>

        <div className="glass-strong rounded-2xl p-8 sm:p-10">
          {/* 1. Introduction / Acceptance of Terms */}
          <h2 className="text-2xl font-semibold text-white mb-4">
            1. Introduction and Acceptance of Terms
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            Welcome to InpromptiFy. These Terms and Conditions (&quot;Terms&quot;) constitute a
            legally binding agreement between you (&quot;User,&quot; &quot;you,&quot; or
            &quot;your&quot;) and InpromptiFy, operated by Miles Cass, located in Perth, Western
            Australia (&quot;InpromptiFy,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            By accessing or using the InpromptiFy platform, website, applications, APIs, or any
            related services (collectively, the &quot;Service&quot;), you acknowledge that you have
            read, understood, and agree to be bound by these Terms. If you do not agree to these
            Terms, you must not access or use the Service.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            If you are using the Service on behalf of an organisation, you represent and warrant that
            you have the authority to bind that organisation to these Terms. In such cases, references
            to &quot;you&quot; and &quot;your&quot; shall include that organisation.
          </p>

          {/* 2. Definitions */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            2. Definitions
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            For the purposes of these Terms, the following definitions apply:
          </p>
          <ul className="list-disc list-inside text-gray-400 leading-relaxed mb-4 space-y-2 ml-2">
            <li>
              <strong className="text-gray-300">&quot;Account&quot;</strong> means the registered
              user account you create to access the Service.
            </li>
            <li>
              <strong className="text-gray-300">&quot;Assessment&quot;</strong> means any AI
              proficiency test, evaluation, quiz, or examination administered through the Service,
              including PromptScore assessments.
            </li>
            <li>
              <strong className="text-gray-300">&quot;Content&quot;</strong> means all text, data,
              information, prompts, responses, scores, feedback, images, and other materials submitted
              to, generated by, or displayed through the Service.
            </li>
            <li>
              <strong className="text-gray-300">&quot;PromptScore&quot;</strong> means the proprietary
              scoring metric used by InpromptiFy to evaluate AI proficiency.
            </li>
            <li>
              <strong className="text-gray-300">&quot;Organisation Account&quot;</strong> means an
              account maintained by a business, enterprise, or other entity for the purpose of
              administering assessments to its members or employees.
            </li>
            <li>
              <strong className="text-gray-300">&quot;Subscription&quot;</strong> means any paid plan
              or recurring billing arrangement that provides access to premium features of the
              Service.
            </li>
          </ul>

          {/* 3. Account Terms */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            3. Account Terms
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            3.1. To access certain features of the Service, you must create an Account. You agree to
            provide accurate, current, and complete information during the registration process and to
            update such information as necessary to keep it accurate, current, and complete.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            3.2. You are solely responsible for maintaining the confidentiality of your Account
            credentials, including your password. You agree to notify us immediately of any
            unauthorised use of your Account or any other breach of security.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            3.3. You must be at least 16 years of age to create an Account. If you are under the age
            of 18, you represent that you have the consent of a parent or legal guardian to use the
            Service.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            3.4. You may not assign or transfer your Account to any third party without our prior
            written consent. You may not create multiple Accounts for the purpose of circumventing
            assessment limits, manipulating scores, or evading enforcement actions.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            3.5. We reserve the right to suspend or terminate any Account that we reasonably believe
            has been created or used in violation of these Terms, without prior notice.
          </p>

          {/* 4. Acceptable Use */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            4. Acceptable Use
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            4.1. You agree to use the Service only for lawful purposes and in accordance with these
            Terms. You shall not use the Service in any manner that could damage, disable,
            overburden, or impair the Service or interfere with any other party&apos;s use of the
            Service.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            4.2. Without limiting the foregoing, you agree not to:
          </p>
          <ul className="list-disc list-inside text-gray-400 leading-relaxed mb-4 space-y-2 ml-2">
            <li>
              Use the Service for any fraudulent, deceptive, or misleading purpose.
            </li>
            <li>
              Upload, transmit, or distribute any viruses, malware, or other harmful code through the
              Service.
            </li>
            <li>
              Attempt to gain unauthorised access to any part of the Service, other users&apos;
              Accounts, or any systems or networks connected to the Service.
            </li>
            <li>
              Use automated scripts, bots, scrapers, or other automated means to access or interact
              with the Service without our express written permission.
            </li>
            <li>
              Harass, abuse, threaten, or intimidate other users of the Service.
            </li>
            <li>
              Misrepresent your identity, qualifications, or affiliation with any person or entity.
            </li>
            <li>
              Use the Service to collect or harvest personal information of other users without their
              consent.
            </li>
            <li>
              Interfere with or disrupt the integrity or performance of the Service.
            </li>
          </ul>

          {/* 5. Assessment Integrity */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            5. Assessment Integrity
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            5.1. The integrity of Assessments is fundamental to the value of the InpromptiFy
            platform. By taking any Assessment, you agree to complete it honestly and independently,
            relying solely on your own knowledge and abilities.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            5.2. During any Assessment, you expressly agree not to:
          </p>
          <ul className="list-disc list-inside text-gray-400 leading-relaxed mb-4 space-y-2 ml-2">
            <li>
              Use any external AI tools, language models, chatbots, or automated assistance to answer
              Assessment questions, unless the Assessment explicitly permits it.
            </li>
            <li>
              Copy, reproduce, share, distribute, or disclose Assessment questions, answers, or
              content in any form, whether publicly or privately.
            </li>
            <li>
              Collaborate with other individuals during an Assessment unless the Assessment is
              explicitly designated as a group exercise.
            </li>
            <li>
              Reverse-engineer, decompile, or attempt to extract the underlying logic, scoring
              methodology, or algorithms used in any Assessment.
            </li>
            <li>
              Use multiple Accounts, browser sessions, or devices to gain an unfair advantage on an
              Assessment.
            </li>
            <li>
              Record, screenshot, or otherwise capture Assessment content for the purpose of
              redistribution or future use.
            </li>
            <li>
              Impersonate another individual or take an Assessment on behalf of another person.
            </li>
          </ul>
          <p className="text-gray-400 leading-relaxed mb-4">
            5.3. We employ technical measures and analytical methods to detect violations of
            Assessment integrity. If we determine, in our sole discretion, that you have engaged in
            any form of cheating or misconduct, we reserve the right to invalidate your Assessment
            results, revoke your PromptScore, suspend or terminate your Account, and notify any
            Organisation Account administrators associated with your assessment.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            5.4. Violations of Assessment integrity may result in a permanent ban from the Service
            and, where applicable, may be reported to relevant employers or educational institutions.
          </p>

          {/* 6. Intellectual Property */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            6. Intellectual Property
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            6.1. The Service, including its design, text, graphics, logos, icons, images, audio,
            software, code, Assessment content, scoring algorithms, and all other materials
            (collectively, &quot;InpromptiFy Materials&quot;), are owned by or licensed to InpromptiFy
            and are protected by copyright, trademark, and other intellectual property laws.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            6.2. You are granted a limited, non-exclusive, non-transferable, revocable licence to
            access and use the Service for its intended purpose, subject to these Terms. This licence
            does not include the right to modify, reproduce, distribute, create derivative works of,
            publicly display, or commercially exploit any InpromptiFy Materials without our prior
            written consent.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            6.3. The InpromptiFy name, logo, PromptScore, and all related trademarks, service marks,
            and trade names are the exclusive property of InpromptiFy. You may not use any of these
            marks without our prior written permission.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            6.4. You retain ownership of any original content you submit to the Service (such as
            prompt responses during Assessments). However, by submitting content, you grant
            InpromptiFy a worldwide, royalty-free, non-exclusive licence to use, reproduce, modify,
            analyse, and display such content for the purposes of operating, improving, and
            developing the Service, including for research and analytics purposes.
          </p>

          {/* 7. Data Usage */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            7. Data Usage
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            7.1. Our collection, use, and handling of personal information is governed by our Privacy
            Policy, which forms part of these Terms. By using the Service, you consent to the
            collection and use of your data as described in the Privacy Policy.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            7.2. We collect and process data including, but not limited to: account registration
            information, Assessment responses and results, usage analytics, device and browser
            information, and interaction data with the Service.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            7.3. We may use aggregated, anonymised, or de-identified data for research, analytics,
            benchmarking, product development, and marketing purposes. Such aggregated data does not
            personally identify you.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            7.4. If you are using the Service through an Organisation Account, your Assessment
            results, PromptScore, and related performance data may be shared with the administrators
            of that Organisation Account. You acknowledge and consent to this sharing when you accept
            an invitation to an Organisation Account.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            7.5. We implement reasonable security measures to protect your data. However, no method of
            electronic transmission or storage is completely secure, and we cannot guarantee absolute
            security of your information.
          </p>

          {/* 8. Payment Terms */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            8. Payment Terms
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            8.1. Certain features of the Service require a paid Subscription. By selecting a paid
            Subscription, you agree to pay the applicable fees as described at the time of purchase.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            8.2. Subscriptions are billed on a recurring basis (monthly or annually, depending on the
            plan selected). Your Subscription will automatically renew at the end of each billing
            cycle unless you cancel it before the renewal date.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            8.3. All fees are quoted in Australian Dollars (AUD) unless otherwise stated. Prices are
            exclusive of applicable taxes, which will be added where required by law.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            8.4. We reserve the right to change Subscription fees at any time. If we increase the
            fees for your current Subscription plan, we will provide you with at least 30 days&apos;
            notice prior to the change taking effect. Your continued use of the Service after the fee
            change constitutes acceptance of the new fees.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            8.5. Refunds are provided at our sole discretion. If you cancel your Subscription before
            the end of a billing cycle, you will retain access to paid features until the end of that
            cycle, but no pro-rata refund will be issued for the remaining period. In circumstances
            where the Service has been materially unavailable or defective, you may request a refund
            by contacting us within 14 days of the issue.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            8.6. If payment fails or your account becomes overdue, we may suspend access to paid
            features until outstanding amounts are resolved. We reserve the right to engage
            third-party collection services for overdue accounts.
          </p>

          {/* 9. Limitation of Liability */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            9. Limitation of Liability
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            9.1. To the maximum extent permitted by applicable law, InpromptiFy and its owner,
            operators, employees, agents, and affiliates shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including but not limited to loss
            of profits, data, business opportunities, or goodwill, arising out of or in connection
            with your use of or inability to use the Service.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            9.2. In no event shall InpromptiFy&apos;s total aggregate liability to you for all claims
            arising out of or relating to these Terms or the Service exceed the total amount you have
            paid to InpromptiFy in the twelve (12) months immediately preceding the event giving rise
            to the claim, or one hundred Australian Dollars (AUD $100), whichever is greater.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            9.3. The Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis,
            without warranties of any kind, whether express or implied, including but not limited to
            implied warranties of merchantability, fitness for a particular purpose, and
            non-infringement.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            9.4. We do not warrant that the Service will be uninterrupted, error-free, secure, or
            free from viruses or other harmful components. We do not guarantee the accuracy,
            completeness, or reliability of any Assessment results, PromptScores, or other data
            provided through the Service.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            9.5. Nothing in these Terms excludes or limits liability that cannot be excluded or
            limited under applicable Australian Consumer Law or other mandatory statutory provisions.
          </p>

          {/* 10. Indemnification */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            10. Indemnification
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            10.1. You agree to indemnify, defend, and hold harmless InpromptiFy, its owner, officers,
            employees, agents, and affiliates from and against any and all claims, damages, losses,
            liabilities, costs, and expenses (including reasonable legal fees) arising out of or in
            connection with:
          </p>
          <ul className="list-disc list-inside text-gray-400 leading-relaxed mb-4 space-y-2 ml-2">
            <li>Your use of or access to the Service.</li>
            <li>Your violation of these Terms.</li>
            <li>Your violation of any applicable law, regulation, or third-party right.</li>
            <li>
              Any content you submit to the Service that infringes or misappropriates the
              intellectual property or other rights of any third party.
            </li>
            <li>
              Any misrepresentation of your Assessment results, PromptScore, or qualifications.
            </li>
          </ul>

          {/* 11. Termination */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            11. Termination
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            11.1. You may terminate your Account at any time by contacting us or using the account
            deletion feature within the Service. Upon termination, your right to access the Service
            will cease immediately.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            11.2. We may suspend or terminate your Account and access to the Service at any time,
            with or without cause, and with or without notice, including but not limited to cases
            where we reasonably believe you have violated these Terms.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            11.3. Upon termination, all licences and rights granted to you under these Terms will
            immediately cease. You remain liable for any obligations incurred prior to termination,
            including outstanding payment obligations.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            11.4. We may retain certain data following termination as required by law or for
            legitimate business purposes, including fraud prevention, enforcement of these Terms, and
            compliance with legal obligations. Aggregated or anonymised data derived from your use of
            the Service may be retained indefinitely.
          </p>

          {/* 12. Modifications to Terms */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            12. Modifications to Terms
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            12.1. We reserve the right to modify these Terms at any time. If we make material changes
            to these Terms, we will provide notice through the Service or by other reasonable means,
            such as email notification, at least 14 days prior to the changes taking effect.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            12.2. Your continued use of the Service following the effective date of any modifications
            constitutes your acceptance of the revised Terms. If you do not agree with the modified
            Terms, you must discontinue your use of the Service and terminate your Account.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            12.3. We will maintain a record of prior versions of these Terms, and the current version
            will always be accessible on our website with the effective date clearly stated.
          </p>

          {/* 13. Governing Law */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            13. Governing Law and Dispute Resolution
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            13.1. These Terms shall be governed by and construed in accordance with the laws of
            Western Australia and the Commonwealth of Australia, without regard to conflict of law
            principles.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            13.2. Any dispute, claim, or controversy arising out of or relating to these Terms or the
            Service shall be subject to the exclusive jurisdiction of the courts of Western Australia,
            Australia. You irrevocably submit to the jurisdiction of those courts.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            13.3. Prior to initiating any formal legal proceedings, you agree to first attempt to
            resolve any dispute informally by contacting us. We will endeavour to resolve any dispute
            within 30 days of receiving your written notice. If the dispute is not resolved within
            that period, either party may pursue formal resolution through the courts.
          </p>
          <p className="text-gray-400 leading-relaxed mb-4">
            13.4. Nothing in this section shall prevent either party from seeking urgent injunctive or
            equitable relief from a court of competent jurisdiction where necessary to prevent
            irreparable harm.
          </p>

          {/* 14. Contact Information */}
          <h2 className="text-2xl font-semibold text-white mt-12 mb-4">
            14. Contact Information
          </h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            If you have any questions, concerns, or requests regarding these Terms and Conditions,
            please contact us at:
          </p>
          <div className="text-gray-400 leading-relaxed mb-4">
            <p className="mb-1">
              <strong className="text-gray-300">InpromptiFy</strong>
            </p>
            <p className="mb-1">Operated by Miles Cass</p>
            <p className="mb-1">Perth, Western Australia, Australia</p>
            <p className="mb-1">
              Email:{" "}
              <a
                href="mailto:legal@inpromptify.com"
                className="text-purple-400 hover:text-purple-300 transition-colors"
              >
                legal@inpromptify.com
              </a>
            </p>
          </div>
          <p className="text-gray-400 leading-relaxed mt-8 pt-8 border-t border-white/10 text-sm">
            By using InpromptiFy, you acknowledge that you have read, understood, and agreed to be
            bound by these Terms and Conditions. Last updated: April 20, 2026.
          </p>
        </div>
      </div>
    </div>
  );
}
