import type { Question } from "./assessment-engine";

// Seed question pool for the public mini-assessment
// In production, these would come from the QuestionBank table
export const QUESTION_POOL: Question[] = [
  {
    id: "q1",
    text: "You need an AI to summarize a 50-page legal contract. Which prompt approach would yield the most accurate and useful summary?",
    options: [
      { id: "A", text: "\"Summarize this contract.\"", isCorrect: false },
      { id: "B", text: "\"Read this legal contract and provide a bullet-point summary of key terms, obligations, deadlines, and liability clauses. Flag any unusual or non-standard provisions.\"", isCorrect: true },
      { id: "C", text: "\"Tell me what this document says.\"", isCorrect: false },
      { id: "D", text: "\"Give me 5 bullet points about this contract.\"", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 30,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["specificity", "legal"],
    maxTimeSeconds: 45,
  },
  {
    id: "q2",
    text: "An AI gives you a Python function with a subtle bug. What is the most effective next prompt?",
    options: [
      { id: "A", text: "\"Fix the bug.\"", isCorrect: false },
      { id: "B", text: "\"This function fails when the input list is empty. Add a guard clause and write a unit test for the edge case.\"", isCorrect: true },
      { id: "C", text: "\"Rewrite the whole function from scratch.\"", isCorrect: false },
      { id: "D", text: "\"Is there a bug in this code?\"", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["iterationIntelligence", "promptQuality"],
    tags: ["debugging", "iteration"],
    maxTimeSeconds: 40,
  },
  {
    id: "q3",
    text: "You want an AI to generate a marketing email that matches your brand voice. What context should you include?",
    options: [
      { id: "A", text: "\"Write a marketing email.\"", isCorrect: false },
      { id: "B", text: "Just the product name and target audience", isCorrect: false },
      { id: "C", text: "Brand voice guidelines, an example of a past email, target audience, CTA goal, and tone preferences", isCorrect: true },
      { id: "D", text: "A link to your website and say \"match this style\"", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 35,
    dimensions: ["promptQuality", "efficiency"],
    tags: ["context", "marketing"],
    maxTimeSeconds: 40,
  },
  {
    id: "q4",
    text: "An AI model generates a response that is factually incorrect but confident. What is the best course of action?",
    options: [
      { id: "A", text: "Accept the response since AI models are generally accurate", isCorrect: false },
      { id: "B", text: "Ask the AI to verify its own answer and provide sources", isCorrect: false },
      { id: "C", text: "Cross-reference with authoritative sources, then prompt the AI with the correct information to regenerate", isCorrect: true },
      { id: "D", text: "Regenerate the response until you get a different answer", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 50,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["verification", "hallucination"],
    maxTimeSeconds: 45,
  },
  {
    id: "q5",
    text: "You need to process 500 customer reviews to extract sentiment and key themes. What is the most efficient approach?",
    options: [
      { id: "A", text: "Send all 500 reviews in one prompt", isCorrect: false },
      { id: "B", text: "Process each review individually with 500 separate prompts", isCorrect: false },
      { id: "C", text: "Batch into groups of 20-30, use a structured output format (JSON), and include a classification schema in the system prompt", isCorrect: true },
      { id: "D", text: "Ask the AI to \"analyze my reviews\" with no further instructions", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 55,
    dimensions: ["efficiency", "promptQuality"],
    tags: ["batching", "structured-output"],
    maxTimeSeconds: 50,
  },
  {
    id: "q6",
    text: "When using chain-of-thought prompting, what is the primary benefit?",
    options: [
      { id: "A", text: "It makes the AI respond faster", isCorrect: false },
      { id: "B", text: "It forces the AI to break down complex reasoning into verifiable steps, improving accuracy on multi-step problems", isCorrect: true },
      { id: "C", text: "It reduces the token count of responses", isCorrect: false },
      { id: "D", text: "It prevents the AI from hallucinating", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["chain-of-thought", "reasoning"],
    maxTimeSeconds: 35,
  },
  {
    id: "q7",
    text: "You are building an AI-powered chatbot. The AI sometimes goes off-topic. What is the most robust solution?",
    options: [
      { id: "A", text: "Tell users not to ask off-topic questions", isCorrect: false },
      { id: "B", text: "Add \"stay on topic\" to the prompt", isCorrect: false },
      { id: "C", text: "Use a system prompt with explicit scope boundaries, role definition, and example interactions showing how to redirect off-topic queries", isCorrect: true },
      { id: "D", text: "Increase the model temperature to get more creative responses", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 60,
    dimensions: ["promptQuality", "iterationIntelligence"],
    tags: ["system-prompt", "guardrails"],
    maxTimeSeconds: 45,
  },
  {
    id: "q8",
    text: "What is the most effective way to get an AI to output data in a specific format?",
    options: [
      { id: "A", text: "Ask nicely and hope it formats correctly", isCorrect: false },
      { id: "B", text: "Provide a concrete example of the desired output format, specify the schema, and use a structured output mode if available", isCorrect: true },
      { id: "C", text: "Just say \"output as JSON\"", isCorrect: false },
      { id: "D", text: "Post-process the output with regex to fix formatting", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 35,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["structured-output", "formatting"],
    maxTimeSeconds: 35,
  },
  {
    id: "q9",
    text: "You're using AI to generate SQL queries. The AI produces a query that works but performs a full table scan on 10M rows. What should you do?",
    options: [
      { id: "A", text: "Run it anyway since the AI generated it", isCorrect: false },
      { id: "B", text: "Ask the AI to \"make it faster\"", isCorrect: false },
      { id: "C", text: "Provide the table schema with indexes, explain the performance requirement, and ask for an optimized query using the available indexes", isCorrect: true },
      { id: "D", text: "Switch to a different AI model", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 65,
    dimensions: ["iterationIntelligence", "efficiency"],
    tags: ["sql", "optimization", "iteration"],
    maxTimeSeconds: 50,
  },
  {
    id: "q10",
    text: "When should you use few-shot examples in a prompt vs. zero-shot?",
    options: [
      { id: "A", text: "Always use few-shot — more examples always means better results", isCorrect: false },
      { id: "B", text: "Use few-shot when the task requires a specific pattern, format, or reasoning style that is hard to describe in words alone", isCorrect: true },
      { id: "C", text: "Never use few-shot because it wastes tokens", isCorrect: false },
      { id: "D", text: "Use zero-shot only when you're in a hurry", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["promptQuality", "efficiency"],
    tags: ["few-shot", "prompt-design"],
    maxTimeSeconds: 40,
  },
  {
    id: "q11",
    text: "An AI assistant is generating inconsistent outputs for the same type of request. What is the most likely fix?",
    options: [
      { id: "A", text: "Lower the temperature to 0 and add a detailed system prompt with explicit formatting rules", isCorrect: true },
      { id: "B", text: "Increase the temperature for more creativity", isCorrect: false },
      { id: "C", text: "Switch to a larger model", isCorrect: false },
      { id: "D", text: "Run the same prompt multiple times and pick the best result", isCorrect: false },
    ],
    correctOptionId: "A",
    difficulty: 50,
    dimensions: ["responseQuality", "speed"],
    tags: ["consistency", "temperature"],
    maxTimeSeconds: 40,
  },
  {
    id: "q12",
    text: "You need to evaluate whether an AI-generated code snippet is production-ready. What should you check?",
    options: [
      { id: "A", text: "Whether it compiles without errors", isCorrect: false },
      { id: "B", text: "Edge cases, error handling, security vulnerabilities, performance implications, and test coverage", isCorrect: true },
      { id: "C", text: "Whether the AI said it was \"production-ready\"", isCorrect: false },
      { id: "D", text: "Only check if it passes the existing test suite", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["responseQuality", "speed"],
    tags: ["code-review", "evaluation"],
    maxTimeSeconds: 40,
  },
  {
    id: "q13",
    text: "You want an AI to role-play as a specific expert for a domain task. What yields the best results?",
    options: [
      { id: "A", text: "\"Pretend you're an expert.\"", isCorrect: false },
      { id: "B", text: "\"You are a senior data engineer with 10 years of experience in ETL pipelines using Apache Spark. You prioritize data quality and idempotent operations. Respond with production-grade solutions.\"", isCorrect: true },
      { id: "C", text: "\"Be smart about this.\"", isCorrect: false },
      { id: "D", text: "\"Answer like a professional would.\"", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["role-prompting", "persona"],
    maxTimeSeconds: 35,
  },
  {
    id: "q14",
    text: "What is the biggest risk of using AI-generated content without review in a customer-facing application?",
    options: [
      { id: "A", text: "The content might be too formal", isCorrect: false },
      { id: "B", text: "Hallucinated facts, brand-inconsistent tone, potential legal/compliance issues, and bias in generated content", isCorrect: true },
      { id: "C", text: "The content will be too short", isCorrect: false },
      { id: "D", text: "Customers will know it was AI-generated", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 35,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["risk", "review"],
    maxTimeSeconds: 35,
  },
  {
    id: "q15",
    text: "You're building an AI workflow that chains 3 prompts together. The second prompt sometimes fails. How do you make this robust?",
    options: [
      { id: "A", text: "Retry the entire chain from the beginning", isCorrect: false },
      { id: "B", text: "Add validation between steps, implement retry with exponential backoff on the failing step, and log intermediate outputs for debugging", isCorrect: true },
      { id: "C", text: "Remove the second prompt and combine its task with the first", isCorrect: false },
      { id: "D", text: "Increase the timeout for all prompts", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["efficiency", "iterationIntelligence"],
    tags: ["chaining", "reliability"],
    maxTimeSeconds: 50,
  },
  {
    id: "q16",
    text: "When is it better to use a smaller, specialized AI model over a large general-purpose one?",
    options: [
      { id: "A", text: "Never — bigger models are always better", isCorrect: false },
      { id: "B", text: "When cost, latency, or data privacy constraints exist and the task is well-defined enough for a fine-tuned smaller model", isCorrect: true },
      { id: "C", text: "Only when the large model is unavailable", isCorrect: false },
      { id: "D", text: "When you want worse results but faster", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["efficiency", "speed"],
    tags: ["model-selection", "optimization"],
    maxTimeSeconds: 40,
  },
];
