import type { Question } from "./assessment-engine";

// Seed question pool for the public mini-assessment
// In production, these would come from the QuestionBank table
export const QUESTION_POOL: Question[] = [
  // ─── PROMPT ENGINEERING (q1–q16) ─────────────────────────────────────────────
  {
    id: "q1",
    text: "You need an AI to summarize a 50-page legal contract. Which prompt approach would yield the most accurate and useful summary?",
    options: [
      { id: "A", text: "\"Summarize this contract.\"", isCorrect: false },
      { id: "B", text: "\"Read this legal contract and provide a bullet-point summary of key terms, obligations, deadlines, and liability clauses. Flag any unusual or non-standard provisions.\"", isCorrect: true },
      { id: "C", text: "\"Tell me what this document says.\"", isCorrect: false },
      { id: "D", text: "\"Give me 5 bullet points about this contract.\"", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 30,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["prompt-engineering", "specificity"],
    maxTimeSeconds: 45,
  },
  {
    id: "q2",
    text: "An AI gives you a Python function with a subtle bug. What is the most effective next prompt?",
    options: [
      { id: "A", text: "\"Fix the bug.\"", isCorrect: false },
      { id: "B", text: "\"This function fails when the input list is empty. Add a guard clause and write a unit test for the edge case.\"", isCorrect: true },
      { id: "C", text: "\"Rewrite the whole function from scratch.\"", isCorrect: false },
      { id: "D", text: "\"Is there a bug in this code?\"", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["iterationIntelligence", "promptQuality"],
    tags: ["prompt-engineering", "debugging"],
    maxTimeSeconds: 40,
  },
  {
    id: "q3",
    text: "You want an AI to generate a marketing email that matches your brand voice. What context should you include?",
    options: [
      { id: "A", text: "\"Write a marketing email.\"", isCorrect: false },
      { id: "B", text: "Just the product name and target audience", isCorrect: false },
      { id: "C", text: "Brand voice guidelines, an example of a past email, target audience, CTA goal, and tone preferences", isCorrect: true },
      { id: "D", text: "A link to your website and say \"match this style\"", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 35,
    dimensions: ["promptQuality", "efficiency"],
    tags: ["prompt-engineering", "context"],
    maxTimeSeconds: 40,
  },
  {
    id: "q4",
    text: "When using chain-of-thought prompting, what is the primary benefit?",
    options: [
      { id: "A", text: "It makes the AI respond faster", isCorrect: false },
      { id: "B", text: "It forces the AI to break down complex reasoning into verifiable steps, improving accuracy on multi-step problems", isCorrect: true },
      { id: "C", text: "It reduces the token count of responses", isCorrect: false },
      { id: "D", text: "It prevents the AI from hallucinating", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["prompt-engineering", "chain-of-thought"],
    maxTimeSeconds: 35,
  },
  {
    id: "q5",
    text: "You are building an AI-powered chatbot. The AI sometimes goes off-topic. What is the most robust solution?",
    options: [
      { id: "A", text: "Tell users not to ask off-topic questions", isCorrect: false },
      { id: "B", text: "Add \"stay on topic\" to the prompt", isCorrect: false },
      { id: "C", text: "Use a system prompt with explicit scope boundaries, role definition, and example interactions showing how to redirect off-topic queries", isCorrect: true },
      { id: "D", text: "Increase the model temperature to get more creative responses", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 60,
    dimensions: ["promptQuality", "iterationIntelligence"],
    tags: ["prompt-engineering", "system-prompts"],
    maxTimeSeconds: 45,
  },
  {
    id: "q6",
    text: "What is the most effective way to get an AI to output data in a specific format?",
    options: [
      { id: "A", text: "Ask nicely and hope it formats correctly", isCorrect: false },
      { id: "B", text: "Provide a concrete example of the desired output format, specify the schema, and use a structured output mode if available", isCorrect: true },
      { id: "C", text: "Just say \"output as JSON\"", isCorrect: false },
      { id: "D", text: "Post-process the output with regex to fix formatting", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 35,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["prompt-engineering", "structured-output"],
    maxTimeSeconds: 35,
  },
  {
    id: "q7",
    text: "When should you use few-shot examples in a prompt vs. zero-shot?",
    options: [
      { id: "A", text: "Always use few-shot — more examples always means better results", isCorrect: false },
      { id: "B", text: "Use few-shot when the task requires a specific pattern, format, or reasoning style that is hard to describe in words alone", isCorrect: true },
      { id: "C", text: "Never use few-shot because it wastes tokens", isCorrect: false },
      { id: "D", text: "Use zero-shot only when you're in a hurry", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["promptQuality", "efficiency"],
    tags: ["prompt-engineering", "few-shot"],
    maxTimeSeconds: 40,
  },
  {
    id: "q8",
    text: "You want an AI to role-play as a specific expert for a domain task. What yields the best results?",
    options: [
      { id: "A", text: "\"Pretend you're an expert.\"", isCorrect: false },
      { id: "B", text: "\"You are a senior data engineer with 10 years of experience in ETL pipelines using Apache Spark. You prioritize data quality and idempotent operations. Respond with production-grade solutions.\"", isCorrect: true },
      { id: "C", text: "\"Be smart about this.\"", isCorrect: false },
      { id: "D", text: "\"Answer like a professional would.\"", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["prompt-engineering", "role-prompting"],
    maxTimeSeconds: 35,
  },
  {
    id: "q9",
    text: "You need to process 500 customer reviews to extract sentiment and key themes. What is the most efficient approach?",
    options: [
      { id: "A", text: "Send all 500 reviews in one prompt", isCorrect: false },
      { id: "B", text: "Process each review individually with 500 separate prompts", isCorrect: false },
      { id: "C", text: "Batch into groups of 20-30, use a structured output format (JSON), and include a classification schema in the system prompt", isCorrect: true },
      { id: "D", text: "Ask the AI to \"analyze my reviews\" with no further instructions", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 55,
    dimensions: ["efficiency", "promptQuality"],
    tags: ["prompt-engineering", "structured-output"],
    maxTimeSeconds: 50,
  },
  {
    id: "q10",
    text: "An AI assistant is generating inconsistent outputs for the same type of request. What is the most likely fix?",
    options: [
      { id: "A", text: "Lower the temperature to 0 and add a detailed system prompt with explicit formatting rules", isCorrect: true },
      { id: "B", text: "Increase the temperature for more creativity", isCorrect: false },
      { id: "C", text: "Switch to a larger model", isCorrect: false },
      { id: "D", text: "Run the same prompt multiple times and pick the best result", isCorrect: false },
    ],
    correctOptionId: "A",
    difficulty: 50,
    dimensions: ["responseQuality", "speed"],
    tags: ["prompt-engineering", "temperature"],
    maxTimeSeconds: 40,
  },
  {
    id: "q11",
    text: "You're writing a prompt that needs to handle both English and Spanish customer inquiries. What's the best approach?",
    options: [
      { id: "A", text: "Write the system prompt in English and hope the model handles Spanish", isCorrect: false },
      { id: "B", text: "Create two entirely separate prompts for each language", isCorrect: false },
      { id: "C", text: "Include bilingual instructions in the system prompt, specify language detection behavior, and provide few-shot examples in both languages", isCorrect: true },
      { id: "D", text: "Translate the user's input to English first, then process it", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 65,
    dimensions: ["promptQuality", "efficiency"],
    tags: ["prompt-engineering", "multilingual"],
    maxTimeSeconds: 50,
  },
  {
    id: "q12",
    text: "When crafting a system prompt for a customer support agent, which element is LEAST important to include?",
    options: [
      { id: "A", text: "Escalation criteria for human handoff", isCorrect: false },
      { id: "B", text: "The model's training data cutoff date", isCorrect: true },
      { id: "C", text: "Tone and personality guidelines", isCorrect: false },
      { id: "D", text: "Boundaries on what the agent should not discuss", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["prompt-engineering", "system-prompts"],
    maxTimeSeconds: 45,
  },
  {
    id: "q13",
    text: "You have a complex prompt that works well but uses 3,000 tokens. Stakeholders want to reduce cost. What's the best optimization?",
    options: [
      { id: "A", text: "Remove all examples and instructions to shorten it", isCorrect: false },
      { id: "B", text: "Switch to a smaller model without changing the prompt", isCorrect: false },
      { id: "C", text: "Refactor verbose instructions into concise directives, replace prose examples with structured templates, and benchmark to ensure quality is maintained", isCorrect: true },
      { id: "D", text: "Truncate the prompt to fit a 1,000 token budget", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 75,
    dimensions: ["efficiency", "promptQuality"],
    tags: ["prompt-engineering", "optimization"],
    maxTimeSeconds: 55,
  },
  {
    id: "q14",
    text: "What is the primary purpose of a 'delimiter' or 'tag' strategy in prompt engineering (e.g., using XML tags or triple backticks)?",
    options: [
      { id: "A", text: "It makes the prompt look more professional", isCorrect: false },
      { id: "B", text: "It clearly separates different sections of input to prevent the model from confusing instructions with user data", isCorrect: true },
      { id: "C", text: "It reduces token count by compressing text", isCorrect: false },
      { id: "D", text: "It forces the model to read the entire prompt before responding", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["prompt-engineering", "structured-output"],
    maxTimeSeconds: 40,
  },
  {
    id: "q15",
    text: "You need to generate product descriptions for 50 items. Each must be unique, 100-150 words, and SEO-optimized. What's the best prompting strategy?",
    options: [
      { id: "A", text: "Send all 50 items at once and ask for descriptions", isCorrect: false },
      { id: "B", text: "Manually write each prompt one at a time", isCorrect: false },
      { id: "C", text: "Create a template prompt with placeholders for product attributes, include one ideal example, specify word count and SEO keywords, then batch process", isCorrect: true },
      { id: "D", text: "Ask the AI to \"write SEO content\" and provide the product list", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 50,
    dimensions: ["efficiency", "promptQuality"],
    tags: ["prompt-engineering", "few-shot"],
    maxTimeSeconds: 45,
  },
  {
    id: "q16",
    text: "You want the model to self-correct by reflecting on its own output before finalizing. Which technique is most appropriate?",
    options: [
      { id: "A", text: "Ask the model to regenerate the response 5 times and pick the longest", isCorrect: false },
      { id: "B", text: "Use a reflection prompt: ask the model to critique its own answer against specific criteria, then produce a revised version", isCorrect: true },
      { id: "C", text: "Set temperature to 0 so the first answer is always correct", isCorrect: false },
      { id: "D", text: "Add \"double-check your work\" at the end of the prompt", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["iterationIntelligence", "responseQuality"],
    tags: ["prompt-engineering", "chain-of-thought"],
    maxTimeSeconds: 45,
  },

  // ─── RAG (q17–q32) ──────────────────────────────────────────────────────────
  {
    id: "q17",
    text: "In a RAG pipeline, what is the primary purpose of the retrieval step?",
    options: [
      { id: "A", text: "To generate the final answer directly", isCorrect: false },
      { id: "B", text: "To fetch relevant context documents that ground the LLM's response in factual, up-to-date information", isCorrect: true },
      { id: "C", text: "To fine-tune the model on new data", isCorrect: false },
      { id: "D", text: "To compress the user's query into fewer tokens", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 25,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["rag", "retrieval"],
    maxTimeSeconds: 35,
  },
  {
    id: "q18",
    text: "You're building a RAG system over a 10,000-page technical manual. What chunking strategy would likely work best?",
    options: [
      { id: "A", text: "Split every 500 characters regardless of content", isCorrect: false },
      { id: "B", text: "One chunk per page", isCorrect: false },
      { id: "C", text: "Semantic chunking by section/subsection boundaries with 100-200 token overlap, preserving headings as metadata", isCorrect: true },
      { id: "D", text: "Store the entire manual as a single chunk", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 55,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["rag", "chunking"],
    maxTimeSeconds: 50,
  },
  {
    id: "q19",
    text: "What is the main advantage of using embedding-based retrieval over keyword search (BM25) in a RAG system?",
    options: [
      { id: "A", text: "Embeddings are always faster than keyword search", isCorrect: false },
      { id: "B", text: "Embeddings capture semantic similarity, so they can match conceptually related content even when exact keywords differ", isCorrect: true },
      { id: "C", text: "Embeddings require less storage than keyword indexes", isCorrect: false },
      { id: "D", text: "Embeddings eliminate the need for a vector database", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["rag", "embedding"],
    maxTimeSeconds: 40,
  },
  {
    id: "q20",
    text: "Your RAG system retrieves 10 relevant chunks but the LLM's context window only fits 5. What's the best approach?",
    options: [
      { id: "A", text: "Randomly select 5 of the 10 chunks", isCorrect: false },
      { id: "B", text: "Always take the first 5 by document order", isCorrect: false },
      { id: "C", text: "Apply a reranker model to score relevance to the query, then select the top 5 most relevant chunks", isCorrect: true },
      { id: "D", text: "Concatenate all 10 and truncate to fit", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 60,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["rag", "reranking"],
    maxTimeSeconds: 45,
  },
  {
    id: "q21",
    text: "A user reports that your RAG chatbot sometimes 'hallucinates' facts not present in the retrieved documents. What is the most effective mitigation?",
    options: [
      { id: "A", text: "Increase the number of retrieved documents to 50", isCorrect: false },
      { id: "B", text: "Add explicit instructions in the system prompt to only answer from provided context, include citation requirements, and add a fallback response for when context is insufficient", isCorrect: true },
      { id: "C", text: "Remove the retrieval step entirely", isCorrect: false },
      { id: "D", text: "Switch to a smaller, less creative model", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["rag", "hallucination"],
    maxTimeSeconds: 50,
  },
  {
    id: "q22",
    text: "Which vector similarity metric is most commonly used for comparing text embeddings in production RAG systems?",
    options: [
      { id: "A", text: "Euclidean distance", isCorrect: false },
      { id: "B", text: "Cosine similarity", isCorrect: true },
      { id: "C", text: "Manhattan distance", isCorrect: false },
      { id: "D", text: "Jaccard similarity", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 35,
    dimensions: ["efficiency", "speed"],
    tags: ["rag", "vector-search"],
    maxTimeSeconds: 30,
  },
  {
    id: "q23",
    text: "You notice your RAG system performs well on factual questions but poorly on 'how-to' queries. What is the most likely issue?",
    options: [
      { id: "A", text: "The LLM is too small", isCorrect: false },
      { id: "B", text: "The embedding model was trained primarily on factual/encyclopedic text and struggles with procedural content — consider a different embedding model or hybrid search", isCorrect: true },
      { id: "C", text: "How-to queries are fundamentally unsolvable with RAG", isCorrect: false },
      { id: "D", text: "You need to increase the chunk size to 10,000 tokens", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["rag", "embedding"],
    maxTimeSeconds: 55,
  },
  {
    id: "q24",
    text: "What is 'hybrid search' in the context of RAG, and when should you use it?",
    options: [
      { id: "A", text: "Using two different LLMs simultaneously", isCorrect: false },
      { id: "B", text: "Combining keyword (BM25) and semantic (vector) search to get the benefits of both exact match and meaning-based retrieval", isCorrect: true },
      { id: "C", text: "Searching across multiple databases at once", isCorrect: false },
      { id: "D", text: "Using both CPU and GPU for faster retrieval", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["rag", "vector-search"],
    maxTimeSeconds: 40,
  },
  {
    id: "q25",
    text: "Your RAG system needs to answer questions about data that changes daily (e.g., inventory levels). What architectural consideration is most critical?",
    options: [
      { id: "A", text: "Use a larger LLM to compensate for stale data", isCorrect: false },
      { id: "B", text: "Re-embed your entire corpus daily", isCorrect: false },
      { id: "C", text: "Implement incremental indexing with a pipeline that detects changed documents, re-embeds only those, and updates the vector store without full reindexing", isCorrect: true },
      { id: "D", text: "Cache all responses for 24 hours", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 75,
    dimensions: ["efficiency", "speed"],
    tags: ["rag", "chunking"],
    maxTimeSeconds: 55,
  },
  {
    id: "q26",
    text: "What is the purpose of adding metadata (e.g., source, date, section title) to chunks in a RAG system?",
    options: [
      { id: "A", text: "It increases the embedding vector dimensions", isCorrect: false },
      { id: "B", text: "It enables filtered retrieval, source attribution in responses, and helps the LLM weigh recency or authority of information", isCorrect: true },
      { id: "C", text: "It replaces the need for a reranker", isCorrect: false },
      { id: "D", text: "It reduces storage costs", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["rag", "chunking"],
    maxTimeSeconds: 40,
  },
  {
    id: "q27",
    text: "A colleague suggests using GPT-4 to generate synthetic questions from your documents to improve retrieval. What is this technique called and why does it help?",
    options: [
      { id: "A", text: "Data augmentation — it makes the documents longer", isCorrect: false },
      { id: "B", text: "HyDE (Hypothetical Document Embeddings) — it bridges the vocabulary gap between user queries and document language by embedding hypothetical answers", isCorrect: true },
      { id: "C", text: "Fine-tuning — it trains the embedding model on your data", isCorrect: false },
      { id: "D", text: "Prompt injection — it forces the model to answer correctly", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 80,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["rag", "embedding"],
    maxTimeSeconds: 60,
  },
  {
    id: "q28",
    text: "You're evaluating embedding models for your RAG pipeline. Which metric best measures retrieval quality?",
    options: [
      { id: "A", text: "Perplexity of the embedding model", isCorrect: false },
      { id: "B", text: "Recall@K — the proportion of relevant documents found in the top K retrieved results", isCorrect: true },
      { id: "C", text: "The size of the embedding vectors", isCorrect: false },
      { id: "D", text: "The model's parameter count", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["rag", "evaluation"],
    maxTimeSeconds: 45,
  },
  {
    id: "q29",
    text: "Your RAG system handles multi-turn conversations. What additional challenge does this introduce compared to single-turn?",
    options: [
      { id: "A", text: "The vector database gets slower with each turn", isCorrect: false },
      { id: "B", text: "You need to reformulate the retrieval query to incorporate conversation history, since the latest user message may reference prior context (e.g., pronouns, follow-ups)", isCorrect: true },
      { id: "C", text: "You need a different embedding model for each turn", isCorrect: false },
      { id: "D", text: "Multi-turn conversations cannot use RAG", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["iterationIntelligence", "promptQuality"],
    tags: ["rag", "retrieval"],
    maxTimeSeconds: 50,
  },
  {
    id: "q30",
    text: "When would you choose a knowledge graph over a vector database as the retrieval backend for RAG?",
    options: [
      { id: "A", text: "When your documents are mostly images", isCorrect: false },
      { id: "B", text: "When relationships between entities matter (e.g., 'Who reports to whom?' or 'Which drug interacts with X?') and traversal queries are more valuable than similarity search", isCorrect: true },
      { id: "C", text: "When you want faster retrieval speeds", isCorrect: false },
      { id: "D", text: "Knowledge graphs are always better than vector databases", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 75,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["rag", "vector-search"],
    maxTimeSeconds: 55,
  },
  {
    id: "q31",
    text: "Your RAG pipeline returns good results but latency is 8 seconds per query. Which optimization would have the biggest impact?",
    options: [
      { id: "A", text: "Switch to a larger LLM for faster processing", isCorrect: false },
      { id: "B", text: "Add an approximate nearest neighbor (ANN) index (e.g., HNSW) to the vector store and reduce the number of retrieved chunks passed to the LLM", isCorrect: true },
      { id: "C", text: "Increase the chunk overlap to 50%", isCorrect: false },
      { id: "D", text: "Store embeddings as 64-bit floats for precision", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["speed", "efficiency"],
    tags: ["rag", "vector-search"],
    maxTimeSeconds: 50,
  },
  {
    id: "q32",
    text: "What is 'context window stuffing' in RAG, and why is it problematic?",
    options: [
      { id: "A", text: "Including too few documents so the model lacks context", isCorrect: false },
      { id: "B", text: "Filling the entire context window with retrieved text, leaving no room for instructions and causing the model to lose focus on the actual query — leading to degraded answer quality", isCorrect: true },
      { id: "C", text: "A technique to maximize model performance by using all available tokens", isCorrect: false },
      { id: "D", text: "Storing the context window in a database for later use", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["rag", "hallucination"],
    maxTimeSeconds: 45,
  },

  // ─── AI AGENTS (q33–q48) ────────────────────────────────────────────────────
  {
    id: "q33",
    text: "What distinguishes an AI 'agent' from a standard LLM chat completion?",
    options: [
      { id: "A", text: "Agents always use larger models", isCorrect: false },
      { id: "B", text: "Agents can autonomously plan, use tools, and take multi-step actions to accomplish goals — rather than just generating text in response to a single prompt", isCorrect: true },
      { id: "C", text: "Agents don't use prompts at all", isCorrect: false },
      { id: "D", text: "Agents are faster than standard completions", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 25,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["agents", "tool-use"],
    maxTimeSeconds: 35,
  },
  {
    id: "q34",
    text: "You're designing a tool-use schema for an AI agent that can search a database and send emails. What's the most important design principle?",
    options: [
      { id: "A", text: "Make each tool do as many things as possible to reduce the number of tools", isCorrect: false },
      { id: "B", text: "Define clear, typed function signatures with descriptions, required/optional parameters, and explicit return types so the model can reliably choose and invoke them", isCorrect: true },
      { id: "C", text: "Let the model figure out the tool format from examples", isCorrect: false },
      { id: "D", text: "Avoid providing descriptions since the function names should be self-explanatory", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["promptQuality", "efficiency"],
    tags: ["agents", "function-calling"],
    maxTimeSeconds: 45,
  },
  {
    id: "q35",
    text: "An AI agent keeps calling the same tool in an infinite loop. What is the most effective fix?",
    options: [
      { id: "A", text: "Remove the tool entirely", isCorrect: false },
      { id: "B", text: "Implement a maximum iteration limit, add loop detection logic, and include explicit stopping criteria in the agent's system prompt", isCorrect: true },
      { id: "C", text: "Increase the model's temperature", isCorrect: false },
      { id: "D", text: "Add more tools so it has other options", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["iterationIntelligence", "efficiency"],
    tags: ["agents", "orchestration"],
    maxTimeSeconds: 45,
  },
  {
    id: "q36",
    text: "In a ReAct (Reasoning + Acting) agent framework, what is the purpose of the 'Thought' step?",
    options: [
      { id: "A", text: "It's decorative text for debugging purposes only", isCorrect: false },
      { id: "B", text: "The model explicitly reasons about what information it has, what it needs, and which action to take next — making its decision process transparent and steerable", isCorrect: true },
      { id: "C", text: "It delays the response to improve quality", isCorrect: false },
      { id: "D", text: "It compresses the conversation history", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["agents", "planning"],
    maxTimeSeconds: 45,
  },
  {
    id: "q37",
    text: "You need an agent to handle complex customer service tasks (refunds, account changes, escalations). How should you implement memory?",
    options: [
      { id: "A", text: "Pass the entire conversation history in every prompt", isCorrect: false },
      { id: "B", text: "Use a sliding window of the last 5 messages only", isCorrect: false },
      { id: "C", text: "Implement tiered memory: short-term (current conversation with summarization), working memory (current task state), and long-term (customer profile from database)", isCorrect: true },
      { id: "D", text: "Don't use memory — each message should be self-contained", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 70,
    dimensions: ["efficiency", "iterationIntelligence"],
    tags: ["agents", "memory"],
    maxTimeSeconds: 55,
  },
  {
    id: "q38",
    text: "What is 'function calling' in the context of modern LLM APIs?",
    options: [
      { id: "A", text: "The model executes code directly on your server", isCorrect: false },
      { id: "B", text: "A structured way for the model to indicate it wants to invoke a specific function with specific arguments, which your application then executes and returns results to the model", isCorrect: true },
      { id: "C", text: "A way to call the API with multiple models simultaneously", isCorrect: false },
      { id: "D", text: "Pre-built functions provided by the API vendor", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 30,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["agents", "function-calling"],
    maxTimeSeconds: 35,
  },
  {
    id: "q39",
    text: "You're building a multi-agent system where one agent writes code and another reviews it. What orchestration pattern is this?",
    options: [
      { id: "A", text: "Swarm intelligence", isCorrect: false },
      { id: "B", text: "A debate/adversarial pattern where specialized agents have distinct roles and cross-check each other's output", isCorrect: true },
      { id: "C", text: "Ensemble learning", isCorrect: false },
      { id: "D", text: "Distributed computing", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["agents", "multi-agent"],
    maxTimeSeconds: 45,
  },
  {
    id: "q40",
    text: "An agent needs to complete a task that requires 5 sequential API calls. After the 3rd call fails with a timeout, what should a well-designed agent do?",
    options: [
      { id: "A", text: "Start the entire 5-step process over from step 1", isCorrect: false },
      { id: "B", text: "Retry step 3 with exponential backoff, and if it continues to fail, report the partial progress and the specific failure point to the user", isCorrect: true },
      { id: "C", text: "Skip step 3 and continue to step 4", isCorrect: false },
      { id: "D", text: "Immediately report failure without any retry", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["iterationIntelligence", "efficiency"],
    tags: ["agents", "orchestration"],
    maxTimeSeconds: 45,
  },
  {
    id: "q41",
    text: "What is the 'tool-use' hallucination problem in AI agents?",
    options: [
      { id: "A", text: "When the agent uses too many tools", isCorrect: false },
      { id: "B", text: "When the model invents tool names that don't exist or fabricates tool responses instead of actually calling them", isCorrect: true },
      { id: "C", text: "When tools return incorrect data", isCorrect: false },
      { id: "D", text: "When the agent forgets which tools are available", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["agents", "tool-use"],
    maxTimeSeconds: 40,
  },
  {
    id: "q42",
    text: "You want to give an agent access to a calculator, web search, and code execution. How should you handle security?",
    options: [
      { id: "A", text: "Trust the model to only use tools appropriately", isCorrect: false },
      { id: "B", text: "Sandbox code execution, rate-limit API calls, validate all tool inputs against schemas, and implement an allowlist of permitted operations", isCorrect: true },
      { id: "C", text: "Only allow one tool at a time", isCorrect: false },
      { id: "D", text: "Disable tools when the model seems confused", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["agents", "tool-use"],
    maxTimeSeconds: 50,
  },
  {
    id: "q43",
    text: "In a planning-based agent architecture, what is the advantage of 'plan-then-execute' over 'step-by-step' reasoning?",
    options: [
      { id: "A", text: "It uses fewer API calls", isCorrect: false },
      { id: "B", text: "The agent creates a complete plan upfront, enabling parallel execution of independent steps, better error recovery, and the ability to revise the plan based on intermediate results", isCorrect: true },
      { id: "C", text: "It always produces better results", isCorrect: false },
      { id: "D", text: "It doesn't need tools", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["efficiency", "iterationIntelligence"],
    tags: ["agents", "planning"],
    maxTimeSeconds: 55,
  },
  {
    id: "q44",
    text: "You're designing a coding agent. It generated code that passes tests but introduces a security vulnerability (SQL injection). How should the system prevent this?",
    options: [
      { id: "A", text: "Add 'write secure code' to the prompt", isCorrect: false },
      { id: "B", text: "Integrate a static analysis/security scanning tool as part of the agent's tool chain, with a separate review step that specifically checks for OWASP top 10 vulnerabilities before accepting code", isCorrect: true },
      { id: "C", text: "Use a model that was trained on secure code only", isCorrect: false },
      { id: "D", text: "Tests passing means the code is safe", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 75,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["agents", "tool-use"],
    maxTimeSeconds: 55,
  },
  {
    id: "q45",
    text: "What is the 'inner monologue' pattern in agent design?",
    options: [
      { id: "A", text: "The agent talks to itself out loud for entertainment", isCorrect: false },
      { id: "B", text: "A hidden reasoning trace where the agent thinks through its approach before responding, allowing complex reasoning without exposing intermediate steps to the user", isCorrect: true },
      { id: "C", text: "A technique where two models debate internally", isCorrect: false },
      { id: "D", text: "Logging all API calls for debugging", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["promptQuality", "iterationIntelligence"],
    tags: ["agents", "planning"],
    maxTimeSeconds: 40,
  },
  {
    id: "q46",
    text: "A multi-agent system has a 'manager' agent that delegates to specialist agents. The manager consistently routes tasks to the wrong specialist. What's the fix?",
    options: [
      { id: "A", text: "Remove the manager and let users pick the specialist", isCorrect: false },
      { id: "B", text: "Provide the manager with clear capability descriptions for each specialist, include routing examples in its prompt, and add a classification step before delegation", isCorrect: true },
      { id: "C", text: "Give all specialists the same capabilities", isCorrect: false },
      { id: "D", text: "Use a random routing strategy", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["promptQuality", "efficiency"],
    tags: ["agents", "multi-agent"],
    maxTimeSeconds: 50,
  },
  {
    id: "q47",
    text: "When should you prefer a single powerful agent over a multi-agent system?",
    options: [
      { id: "A", text: "Multi-agent systems are always better", isCorrect: false },
      { id: "B", text: "When the task is well-defined, doesn't require diverse expertise, and the added latency/complexity of inter-agent communication would outweigh the benefits", isCorrect: true },
      { id: "C", text: "Single agents can't use tools, so never", isCorrect: false },
      { id: "D", text: "Only when budget is a concern", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["efficiency", "speed"],
    tags: ["agents", "multi-agent"],
    maxTimeSeconds: 45,
  },
  {
    id: "q48",
    text: "Your agent has access to a 'delete_record' tool. A user asks: 'Delete all records from last month.' What safety pattern should be implemented?",
    options: [
      { id: "A", text: "Execute immediately since the user explicitly requested it", isCorrect: false },
      { id: "B", text: "Refuse to delete anything ever", isCorrect: false },
      { id: "C", text: "Implement a confirmation step: show the user exactly which records would be affected and their count, require explicit approval before executing destructive actions", isCorrect: true },
      { id: "D", text: "Delete one record at a time with a delay between each", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 45,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["agents", "tool-use"],
    maxTimeSeconds: 40,
  },

  // ─── EVALUATION (q49–q64) ───────────────────────────────────────────────────
  {
    id: "q49",
    text: "You need to evaluate the quality of AI-generated summaries. Which metric best captures whether the summary preserves the source document's key information?",
    options: [
      { id: "A", text: "BLEU score", isCorrect: false },
      { id: "B", text: "ROUGE-L, which measures the longest common subsequence between the generated summary and reference, capturing content overlap and ordering", isCorrect: true },
      { id: "C", text: "Word count comparison", isCorrect: false },
      { id: "D", text: "Sentiment analysis of the summary", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["evaluation", "automated-metrics"],
    maxTimeSeconds: 45,
  },
  {
    id: "q50",
    text: "What is the primary limitation of using BLEU scores to evaluate open-ended AI text generation?",
    options: [
      { id: "A", text: "BLEU is too slow to compute", isCorrect: false },
      { id: "B", text: "BLEU measures n-gram overlap with a reference, penalizing valid paraphrases and creative responses that convey the same meaning with different words", isCorrect: true },
      { id: "C", text: "BLEU only works for English text", isCorrect: false },
      { id: "D", text: "BLEU requires GPU acceleration", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["evaluation", "automated-metrics"],
    maxTimeSeconds: 45,
  },
  {
    id: "q51",
    text: "You're setting up A/B testing for two different prompt versions in production. What's the most critical factor to control?",
    options: [
      { id: "A", text: "Ensure both prompts use the same model at the same temperature with the same traffic split and evaluation criteria — isolating the prompt as the only variable", isCorrect: true },
      { id: "B", text: "Run each prompt for a different week", isCorrect: false },
      { id: "C", text: "Test on your team's queries only", isCorrect: false },
      { id: "D", text: "Use the cheapest model to save costs during testing", isCorrect: false },
    ],
    correctOptionId: "A",
    difficulty: 50,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["evaluation", "ab-testing"],
    maxTimeSeconds: 45,
  },
  {
    id: "q52",
    text: "What is 'red teaming' in the context of AI evaluation?",
    options: [
      { id: "A", text: "Testing the model's performance on benchmark datasets", isCorrect: false },
      { id: "B", text: "Systematically probing the model for failures, biases, safety issues, and adversarial vulnerabilities by intentionally trying to make it behave badly", isCorrect: true },
      { id: "C", text: "A/B testing with a red and blue group", isCorrect: false },
      { id: "D", text: "Measuring response latency under load", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["evaluation", "red-teaming"],
    maxTimeSeconds: 35,
  },
  {
    id: "q53",
    text: "You want to use an LLM as a judge to evaluate other LLM outputs. What is the biggest risk of this approach?",
    options: [
      { id: "A", text: "It's too expensive", isCorrect: false },
      { id: "B", text: "LLM judges exhibit systematic biases: position bias (preferring the first option), verbosity bias (preferring longer answers), and self-enhancement bias (preferring outputs from their own model family)", isCorrect: true },
      { id: "C", text: "LLMs cannot compare two texts", isCorrect: false },
      { id: "D", text: "It requires fine-tuning the judge model", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["evaluation", "automated-metrics"],
    maxTimeSeconds: 55,
  },
  {
    id: "q54",
    text: "You need to establish a human evaluation pipeline for your AI's customer service responses. What framework produces the most reliable results?",
    options: [
      { id: "A", text: "Have one person rate all responses on a 1-10 scale", isCorrect: false },
      { id: "B", text: "Use multiple annotators with a structured rubric (specific criteria like accuracy, helpfulness, tone), measure inter-annotator agreement (Cohen's kappa), and calibrate with gold-standard examples", isCorrect: true },
      { id: "C", text: "Ask customers to rate responses with a thumbs up/down", isCorrect: false },
      { id: "D", text: "Compare response length as a proxy for quality", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["evaluation", "human-eval"],
    maxTimeSeconds: 50,
  },
  {
    id: "q55",
    text: "Your AI model scores 92% on your benchmark dataset but users report poor real-world performance. What is the most likely explanation?",
    options: [
      { id: "A", text: "Users are using the model incorrectly", isCorrect: false },
      { id: "B", text: "The benchmark doesn't represent real-world query distribution — it may lack edge cases, adversarial inputs, or domain-specific scenarios that users actually encounter", isCorrect: true },
      { id: "C", text: "92% is too low — you need 99%+", isCorrect: false },
      { id: "D", text: "The model has been overfitting to the benchmark", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["evaluation", "benchmarking"],
    maxTimeSeconds: 45,
  },
  {
    id: "q56",
    text: "What is 'contamination' in AI benchmarking, and why does it matter?",
    options: [
      { id: "A", text: "When the test data is corrupted", isCorrect: false },
      { id: "B", text: "When the model was trained on data that overlaps with the benchmark test set, artificially inflating scores and making them unreliable as a measure of true capability", isCorrect: true },
      { id: "C", text: "When two benchmarks measure the same thing", isCorrect: false },
      { id: "D", text: "When the benchmark is too easy", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["evaluation", "benchmarking"],
    maxTimeSeconds: 40,
  },
  {
    id: "q57",
    text: "You've deployed a new prompt and want to monitor its quality in production. Which approach provides the most actionable signal?",
    options: [
      { id: "A", text: "Monitor average response time only", isCorrect: false },
      { id: "B", text: "Track a combination of: automated quality scores (LLM-as-judge on a sample), user feedback signals (thumbs up/down, regeneration rate), and business metrics (task completion rate, escalation rate)", isCorrect: true },
      { id: "C", text: "Read every response manually", isCorrect: false },
      { id: "D", text: "Compare output length to a baseline", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["evaluation", "automated-metrics"],
    maxTimeSeconds: 50,
  },
  {
    id: "q58",
    text: "When building an evaluation dataset for a domain-specific AI (e.g., medical Q&A), what is the minimum viable approach?",
    options: [
      { id: "A", text: "Use a general-purpose benchmark like MMLU", isCorrect: false },
      { id: "B", text: "Curate 50-100 representative questions from real user queries, have domain experts write gold-standard answers, and define scoring rubrics for each question", isCorrect: true },
      { id: "C", text: "Generate test questions using another LLM", isCorrect: false },
      { id: "D", text: "Use the first 100 questions from your production logs without review", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["evaluation", "benchmarking"],
    maxTimeSeconds: 50,
  },
  {
    id: "q59",
    text: "What is the key advantage of using 'Elo ratings' to evaluate LLM performance?",
    options: [
      { id: "A", text: "It only requires a single evaluation per model", isCorrect: false },
      { id: "B", text: "It provides a relative ranking through pairwise comparisons, which is often more reliable than absolute scores because humans find it easier to judge 'A is better than B' than to assign a numeric score", isCorrect: true },
      { id: "C", text: "It works without human evaluators", isCorrect: false },
      { id: "D", text: "It measures speed, not quality", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["evaluation", "human-eval"],
    maxTimeSeconds: 50,
  },
  {
    id: "q60",
    text: "You're comparing two models and Model A scores higher on ROUGE but lower on human preference. Which should you trust?",
    options: [
      { id: "A", text: "Always trust the automated metric", isCorrect: false },
      { id: "B", text: "Human preference, because automated metrics measure surface-level text overlap while humans evaluate coherence, usefulness, and correctness holistically — but investigate why the metrics diverge", isCorrect: true },
      { id: "C", text: "Average both scores", isCorrect: false },
      { id: "D", text: "Neither — run more benchmarks", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["evaluation", "human-eval"],
    maxTimeSeconds: 45,
  },
  {
    id: "q61",
    text: "What is 'regression testing' in the context of AI/LLM applications?",
    options: [
      { id: "A", text: "Testing for statistical regression in model weights", isCorrect: false },
      { id: "B", text: "Running a fixed set of test cases after any change (prompt update, model upgrade, parameter change) to ensure previously working functionality hasn't degraded", isCorrect: true },
      { id: "C", text: "Testing the model on progressively harder questions", isCorrect: false },
      { id: "D", text: "Reverting to a previous model version", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 35,
    dimensions: ["efficiency", "speed"],
    tags: ["evaluation", "benchmarking"],
    maxTimeSeconds: 35,
  },
  {
    id: "q62",
    text: "You need to evaluate whether your AI generates factually accurate responses about medical topics. Which evaluation strategy is most appropriate?",
    options: [
      { id: "A", text: "Use BLEU score against medical textbook excerpts", isCorrect: false },
      { id: "B", text: "Have licensed medical professionals review a stratified sample of responses using a rubric that checks factual accuracy, completeness, and potential for harm", isCorrect: true },
      { id: "C", text: "Check if the responses match Wikipedia articles", isCorrect: false },
      { id: "D", text: "Use an LLM to verify the medical claims", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["evaluation", "human-eval"],
    maxTimeSeconds: 40,
  },
  {
    id: "q63",
    text: "What makes a good 'golden dataset' for evaluating an AI system?",
    options: [
      { id: "A", text: "As many examples as possible, regardless of quality", isCorrect: false },
      { id: "B", text: "A curated, representative sample with expert-validated ground truth answers, covering common cases, edge cases, and adversarial inputs in proportion to their real-world frequency", isCorrect: true },
      { id: "C", text: "Only the hardest questions to stress-test the model", isCorrect: false },
      { id: "D", text: "Questions generated by the same AI model being evaluated", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["evaluation", "benchmarking"],
    maxTimeSeconds: 45,
  },
  {
    id: "q64",
    text: "You're running an A/B test on two prompts and after 100 interactions, Prompt B has a 2% higher satisfaction score. Should you ship Prompt B?",
    options: [
      { id: "A", text: "Yes — any improvement is worth shipping", isCorrect: false },
      { id: "B", text: "Check statistical significance (p-value, confidence intervals), ensure the sample size is adequate for the effect size, segment by user type to check for subgroup effects, and consider practical significance vs. statistical significance", isCorrect: true },
      { id: "C", text: "No — 2% is too small to matter", isCorrect: false },
      { id: "D", text: "Run for 1,000 more interactions regardless", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 75,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["evaluation", "ab-testing"],
    maxTimeSeconds: 55,
  },

  // ─── SAFETY & ETHICS (q65–q80) ──────────────────────────────────────────────
  {
    id: "q65",
    text: "What is the biggest risk of using AI-generated content without review in a customer-facing application?",
    options: [
      { id: "A", text: "The content might be too formal", isCorrect: false },
      { id: "B", text: "Hallucinated facts, brand-inconsistent tone, potential legal/compliance issues, and bias in generated content", isCorrect: true },
      { id: "C", text: "The content will be too short", isCorrect: false },
      { id: "D", text: "Customers will know it was AI-generated", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 35,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["safety-ethics", "guardrails"],
    maxTimeSeconds: 35,
  },
  {
    id: "q66",
    text: "What is 'prompt injection' and how does it differ from 'jailbreaking'?",
    options: [
      { id: "A", text: "They are the same thing", isCorrect: false },
      { id: "B", text: "Prompt injection tricks the model into treating user data as instructions (e.g., 'Ignore above instructions and...'), while jailbreaking specifically aims to bypass the model's safety training and content policies", isCorrect: true },
      { id: "C", text: "Prompt injection is a server-side attack; jailbreaking is client-side", isCorrect: false },
      { id: "D", text: "Jailbreaking is illegal; prompt injection is not", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 55,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["safety-ethics", "prompt-injection"],
    maxTimeSeconds: 45,
  },
  {
    id: "q67",
    text: "You discover your AI hiring tool recommends male candidates 20% more often than equally qualified female candidates. What is the root cause and fix?",
    options: [
      { id: "A", text: "The model is correct — ignore it", isCorrect: false },
      { id: "B", text: "The training data likely reflects historical hiring bias. Fix: audit the training data for demographic imbalance, implement fairness constraints, test for disparate impact across protected groups, and add bias monitoring to production", isCorrect: true },
      { id: "C", text: "Remove gender from the input features and the bias will disappear", isCorrect: false },
      { id: "D", text: "Add an equal number of male and female examples to the prompt", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["safety-ethics", "bias"],
    maxTimeSeconds: 50,
  },
  {
    id: "q68",
    text: "What is RLHF (Reinforcement Learning from Human Feedback) and why is it important?",
    options: [
      { id: "A", text: "A technique to make models faster", isCorrect: false },
      { id: "B", text: "A training approach where human preferences are used to fine-tune model behavior, helping align the model's outputs with human values, safety requirements, and quality expectations", isCorrect: true },
      { id: "C", text: "A way to evaluate models using reinforcement learning", isCorrect: false },
      { id: "D", text: "A type of prompt engineering technique", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["safety-ethics", "alignment"],
    maxTimeSeconds: 40,
  },
  {
    id: "q69",
    text: "Your company wants to use customer emails to fine-tune an AI model. What data privacy concern should you address first?",
    options: [
      { id: "A", text: "Whether the emails are in English", isCorrect: false },
      { id: "B", text: "Whether you have explicit consent to use the data for AI training, whether PII needs to be removed/anonymized, compliance with GDPR/CCPA, and whether the fine-tuned model could memorize and regurgitate private data", isCorrect: true },
      { id: "C", text: "Whether the emails are long enough for training", isCorrect: false },
      { id: "D", text: "Whether competitors might use the same data", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["safety-ethics", "data-privacy"],
    maxTimeSeconds: 45,
  },
  {
    id: "q70",
    text: "What are 'guardrails' in the context of AI deployment, and name one input guardrail and one output guardrail.",
    options: [
      { id: "A", text: "Physical barriers around AI servers", isCorrect: false },
      { id: "B", text: "Automated checks that constrain AI behavior — input: topic classification to block off-topic/malicious requests; output: content filtering to catch toxic, biased, or policy-violating responses before they reach the user", isCorrect: true },
      { id: "C", text: "Rate limiting on API calls", isCorrect: false },
      { id: "D", text: "Terms of service that users must agree to", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["promptQuality", "responseQuality"],
    tags: ["safety-ethics", "guardrails"],
    maxTimeSeconds: 45,
  },
  {
    id: "q71",
    text: "An AI content moderation system flags 30% of legitimate posts as toxic (high false positive rate). What's the best approach to improve it?",
    options: [
      { id: "A", text: "Lower the toxicity threshold to flag fewer posts", isCorrect: false },
      { id: "B", text: "Analyze the false positives to identify patterns (e.g., sarcasm, AAVE, medical terms), add these to your evaluation set, fine-tune or adjust the classifier, and implement a human review queue for borderline cases", isCorrect: true },
      { id: "C", text: "Remove the moderation system entirely", isCorrect: false },
      { id: "D", text: "Use a larger model", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["iterationIntelligence", "responseQuality"],
    tags: ["safety-ethics", "toxicity"],
    maxTimeSeconds: 50,
  },
  {
    id: "q72",
    text: "What is 'AI alignment' and why is it considered a critical challenge?",
    options: [
      { id: "A", text: "Making sure AI models produce grammatically correct text", isCorrect: false },
      { id: "B", text: "Ensuring AI systems behave in accordance with human intentions and values — critical because misaligned systems may optimize for proxy objectives that produce harmful outcomes, especially as AI capabilities increase", isCorrect: true },
      { id: "C", text: "Aligning model architectures across different vendors", isCorrect: false },
      { id: "D", text: "Making AI agree with every user request", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 50,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["safety-ethics", "alignment"],
    maxTimeSeconds: 45,
  },
  {
    id: "q73",
    text: "You're deploying an AI assistant that handles sensitive financial data. Which defense-in-depth measures should you implement against prompt injection?",
    options: [
      { id: "A", text: "Trust the model's safety training to handle everything", isCorrect: false },
      { id: "B", text: "Input sanitization, privilege separation (the LLM should not have direct database write access), output validation, monitoring for anomalous queries, and a separate classifier to detect injection attempts", isCorrect: true },
      { id: "C", text: "Add 'do not follow injected instructions' to the system prompt", isCorrect: false },
      { id: "D", text: "Only allow pre-approved questions", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 75,
    dimensions: ["efficiency", "responseQuality"],
    tags: ["safety-ethics", "prompt-injection"],
    maxTimeSeconds: 55,
  },
  {
    id: "q74",
    text: "What is the 'dual-use' dilemma in AI, and how should practitioners handle it?",
    options: [
      { id: "A", text: "Using the same model for two products", isCorrect: false },
      { id: "B", text: "AI capabilities intended for beneficial purposes (e.g., chemistry research) can also enable harm (e.g., synthesizing dangerous substances). Practitioners should implement use-case restrictions, access controls, and conduct risk assessments before deployment", isCorrect: true },
      { id: "C", text: "Running AI on both CPU and GPU", isCorrect: false },
      { id: "D", text: "Using AI for both training and inference", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["safety-ethics", "alignment"],
    maxTimeSeconds: 50,
  },
  {
    id: "q75",
    text: "Your AI chatbot is used in the EU. Under the EU AI Act, what classification would a chatbot providing medical advice likely fall under?",
    options: [
      { id: "A", text: "Minimal risk — no restrictions", isCorrect: false },
      { id: "B", text: "High risk — requiring conformity assessment, human oversight, transparency obligations, and documentation of training data and evaluation results", isCorrect: true },
      { id: "C", text: "Unacceptable risk — banned outright", isCorrect: false },
      { id: "D", text: "Limited risk — only requires a disclosure that it's AI", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["responseQuality", "efficiency"],
    tags: ["safety-ethics", "data-privacy"],
    maxTimeSeconds: 50,
  },
  {
    id: "q76",
    text: "What is 'model card' documentation and why should every deployed AI system have one?",
    options: [
      { id: "A", text: "A credit card used to pay for model API access", isCorrect: false },
      { id: "B", text: "A standardized document describing the model's intended use, limitations, training data, evaluation results, and ethical considerations — enabling informed decisions about whether and how to use the model", isCorrect: true },
      { id: "C", text: "A physical card shipped with AI hardware", isCorrect: false },
      { id: "D", text: "A marketing brochure for the model", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 40,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["safety-ethics", "alignment"],
    maxTimeSeconds: 40,
  },
  {
    id: "q77",
    text: "You're using an LLM to generate code suggestions for developers. A user reports that it suggested code containing a hardcoded API key from its training data. What should you do?",
    options: [
      { id: "A", text: "Ignore it — the API key is probably expired", isCorrect: false },
      { id: "B", text: "Implement output scanning for patterns matching secrets (API keys, passwords, tokens), add this to your regression test suite, report the memorization issue to the model provider, and review your prompt for patterns that might trigger memorized content", isCorrect: true },
      { id: "C", text: "Add 'don't output API keys' to the prompt", isCorrect: false },
      { id: "D", text: "Switch to a different model", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["iterationIntelligence", "responseQuality"],
    tags: ["safety-ethics", "data-privacy"],
    maxTimeSeconds: 50,
  },
  {
    id: "q78",
    text: "What is 'Constitutional AI' and how does it relate to RLHF?",
    options: [
      { id: "A", text: "AI that follows the US Constitution", isCorrect: false },
      { id: "B", text: "An approach where the model is trained to follow a set of principles ('constitution') for self-critique and revision, reducing the need for extensive human feedback while maintaining alignment — it extends RLHF by making the reward model more principled", isCorrect: true },
      { id: "C", text: "A legal framework for AI regulation", isCorrect: false },
      { id: "D", text: "A model architecture named after the Constitutional Convention", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 80,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["safety-ethics", "alignment"],
    maxTimeSeconds: 55,
  },
  {
    id: "q79",
    text: "Your team is building an AI that generates job postings. Testing reveals it uses gendered language ('rockstar developer', 'nurturing team lead'). What's the most systematic fix?",
    options: [
      { id: "A", text: "Manually review every generated posting", isCorrect: false },
      { id: "B", text: "Implement a bias detection classifier in the output pipeline that flags gendered/exclusionary language, create a debiasing prompt layer, build an evaluation set of known biased patterns, and regularly audit outputs across demographic dimensions", isCorrect: true },
      { id: "C", text: "Add 'be gender neutral' to the prompt", isCorrect: false },
      { id: "D", text: "Only generate bullet-point postings to avoid natural language bias", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 65,
    dimensions: ["iterationIntelligence", "responseQuality"],
    tags: ["safety-ethics", "bias"],
    maxTimeSeconds: 50,
  },
  {
    id: "q80",
    text: "When is it ethically necessary to disclose that content was generated by AI?",
    options: [
      { id: "A", text: "Only when legally required", isCorrect: false },
      { id: "B", text: "Whenever a reasonable person would want to know — especially in contexts where trust, expertise, or authorship matters (medical advice, legal documents, news articles, academic work, customer interactions)", isCorrect: true },
      { id: "C", text: "Never — AI content is indistinguishable from human content", isCorrect: false },
      { id: "D", text: "Only when the AI makes a mistake", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 30,
    dimensions: ["responseQuality", "promptQuality"],
    tags: ["safety-ethics", "alignment"],
    maxTimeSeconds: 35,
  },
  {
    id: "q81",
    text: "You're using AI to generate SQL queries. The AI produces a query that works but performs a full table scan on 10M rows. What should you do?",
    options: [
      { id: "A", text: "Run it anyway since the AI generated it", isCorrect: false },
      { id: "B", text: "Ask the AI to \"make it faster\"", isCorrect: false },
      { id: "C", text: "Provide the table schema with indexes, explain the performance requirement, and ask for an optimized query using the available indexes", isCorrect: true },
      { id: "D", text: "Switch to a different AI model", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 65,
    dimensions: ["iterationIntelligence", "efficiency"],
    tags: ["prompt-engineering", "optimization"],
    maxTimeSeconds: 50,
  },
  {
    id: "q82",
    text: "You need to evaluate whether an AI-generated code snippet is production-ready. What should you check?",
    options: [
      { id: "A", text: "Whether it compiles without errors", isCorrect: false },
      { id: "B", text: "Edge cases, error handling, security vulnerabilities, performance implications, and test coverage", isCorrect: true },
      { id: "C", text: "Whether the AI said it was \"production-ready\"", isCorrect: false },
      { id: "D", text: "Only check if it passes the existing test suite", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 45,
    dimensions: ["responseQuality", "speed"],
    tags: ["evaluation", "code-review"],
    maxTimeSeconds: 40,
  },
  {
    id: "q83",
    text: "You're building an AI workflow that chains 3 prompts together. The second prompt sometimes fails. How do you make this robust?",
    options: [
      { id: "A", text: "Retry the entire chain from the beginning", isCorrect: false },
      { id: "B", text: "Add validation between steps, implement retry with exponential backoff on the failing step, and log intermediate outputs for debugging", isCorrect: true },
      { id: "C", text: "Remove the second prompt and combine its task with the first", isCorrect: false },
      { id: "D", text: "Increase the timeout for all prompts", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 70,
    dimensions: ["efficiency", "iterationIntelligence"],
    tags: ["agents", "orchestration"],
    maxTimeSeconds: 50,
  },
  {
    id: "q84",
    text: "When is it better to use a smaller, specialized AI model over a large general-purpose one?",
    options: [
      { id: "A", text: "Never — bigger models are always better", isCorrect: false },
      { id: "B", text: "When cost, latency, or data privacy constraints exist and the task is well-defined enough for a fine-tuned smaller model", isCorrect: true },
      { id: "C", text: "Only when the large model is unavailable", isCorrect: false },
      { id: "D", text: "When you want worse results but faster", isCorrect: false },
    ],
    correctOptionId: "B",
    difficulty: 60,
    dimensions: ["efficiency", "speed"],
    tags: ["evaluation", "optimization"],
    maxTimeSeconds: 40,
  },
  {
    id: "q85",
    text: "An AI model generates a response that is factually incorrect but confident. What is the best course of action?",
    options: [
      { id: "A", text: "Accept the response since AI models are generally accurate", isCorrect: false },
      { id: "B", text: "Ask the AI to verify its own answer and provide sources", isCorrect: false },
      { id: "C", text: "Cross-reference with authoritative sources, then prompt the AI with the correct information to regenerate", isCorrect: true },
      { id: "D", text: "Regenerate the response until you get a different answer", isCorrect: false },
    ],
    correctOptionId: "C",
    difficulty: 50,
    dimensions: ["responseQuality", "iterationIntelligence"],
    tags: ["safety-ethics", "hallucination"],
    maxTimeSeconds: 45,
  },
];
